// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"us-data/internal/app"
	"us-data/internal/provider"
)

// Injectors from wire.go:

// InitializeApp builds App (Config + DataProvider) via Wire.
// Caller must call a.DP.Close() when done.
func InitializeApp() (*App, error) {
	config := app.ProvideConfig()
	packetSaver, err := app.ProvidePacketSaver(config)
	if err != nil {
		return nil, err
	}
	polygonProvider, err := app.ProvidePolygonProvider(config, packetSaver)
	if err != nil {
		return nil, err
	}
	mainApp := &App{
		Config: config,
		DP:     polygonProvider,
	}
	return mainApp, nil
}

// wire.go:

// App holds application dependencies built by Wire.
type App struct {
	Config *app.Config
	DP     provider.DataProvider
}
